### ISSUE TITLE
Country is effectively a required field.

### ISSUE THREAD

**Issue by dotancohen** [nlemoine/acf-country#8]
There seems to be no way to have `county` be not required. Even setting the `required` field to 0 and the `default_value` field to an empty string will have ACF Country use the first country (Afganistan in English) as the default.

**Comment by nlemoine** [comment]
Should be fixed now.

**Comment by dotancohen** [comment]
Thank you!

**Comment by dotancohen** [comment]
The current fix does not resolve the issue. A NULL country (empty <option>) must be prepended to the list to resolve the issue.

**Comment by dotancohen** [comment]
See pull request with tested fix:
https://github.com/nlemoine/acf-country/pull/9

**Comment by nlemoine** [comment]
The fix does work for me. The empty option is added here: https://github.com/nlemoine/acf-country/blob/master/fields/acf-country-helpers.php#L62-L64

Tested with with native select and select2. 

Could you tell me more about your field options?

**Comment by trantin2310** [comment]
the empty option not working for me after you fixed. 

please check with screenshot and i will you login website detail for you checking.
login:
http://122.201.118.65/~pickadevelop/wp-admin/
username: admin
password: admin

check image link 
https://www.awesomescreenshot.com/image/3115175/51ec6fa8dad0f5043b5b4894202dc3cd
check product link with country file called country_selling
http://122.201.118.65/~pickadevelop/wp-admin/post.php?post=96696&action=edit

hope you will help me solve soon.
